### PR TITLE
Cset comparison new info panel

### PR DESCRIPTION
**Pull request by mtj0712**
Resolved issue #390. Please review and comment on any changes that should be made.

### CODE REVIEW

**Comment by Sigfried** [comment]
Looking good. 

Big issue (my fault): the columns showing the different concept sets being compared and which concepts belong to each (with flags) aren't showing up. Let me know if you want help with that. It might not be that easy to do.

@hlehmann17 also wanted the column names to be the same as in the interface: same capitalization, spaces, etc. Of the column in the download that don't appear in the interface, instructions and order of appearance:
  - level: move to first column; rename to "Level"
  - concept_code: after Vocabulary; rename to "Concept code"
  - concept_class_id: rename to "Concept class"
  - domain_id: rename to "Concept domain"
  - domain: rename to "Domain tables with concept"
  - domain_cnt: rename to "Domain count"
  - standard_concept: rename to "OMOP standard"
  - invalid_reason: rename to "Invalid reason"
  - pathToRoot: don't include
  - hasChildren: don't include

**Comment by mtj0712** [comment]
For some reason, "click to add/remove" pop-up only appears when the developer tool (F12) is open.

**Comment by joeflack4** [comment]
That is super weird! If it continues to happen and you want help, if you could send me a screenshot of what you're clicking, I can check out the branch and help troubleshoot.

**Comment by Sigfried** [comment]
Resolved column names and adding concept set columns.

**Pull request merged**
